### PR TITLE
Test cases of the project

### PR DESCRIPTION
**Pull request by kavyaram15**
1. signup function validation
2.  login function validation
3.  main_menu function validation
4.  cancel_trip validation
5. view_print_trip validation

### CODE REVIEW

**Comment by ramyathammineni** [comment]
For email validation unable to maintain the substrings like the (@gmail.com, @hotmail.com etc.,)

**Comment by imsarahkhan** [comment]
Let's try to implement the functionality of the basic test cases as many fail to work or are difficult to implement.

**Comment by kavyaram15** [comment]
Try implement the email validation by at least that it contains '@' string - basic testing can be performed using this

**Comment by imsarahkhan** [comment]
The main menu test case for letters or special characters does not work.  Difficulties in implementing the test case code.

**Comment by ramyathammineni** [comment]
Ok. Basic test cases are implemented for the email validation that it contains '@' as a substring as the combination of other ways is more difficult.

**Comment by imsarahkhan** [comment]
Test cases for vie/print and cancel functions are still pending.

**Comment by kavyaram15** [comment]
Username validation should be done - Comes under the signup function validation

**Comment by imsarahkhan** [comment]
Username validation is done under both signup and login functionalities.

**Comment by ramyathammineni** [comment]
Password validation should be done in signup and login functionalities

**Comment by kavyaram15** [comment]
Password validation is implemented as per the specifications

**Comment by ramyathammineni** [comment]
The booking ID validation is implemented

**Comment by kavyaram15** [comment]
Some test cases are redundant for Login and Signup functionalities

**Comment by imsarahkhan** [comment]
Let's write only one test case if there are redundant test cases. 

> Some test cases are redundant for Login and Signup functionalities

**Comment by ramyathammineni** [comment]
view_print trip test cases are implemented

**Comment by kavyaram15** [comment]
cancel_trip test cases are implemented

**Comment by kavyaram15** [comment]
unity.h library unable to apply to our project because there is some issue in importing in the clion

**Review by imsarahkhan — COMMENTED** [review]
Automated Testing will not be possible with the issues being faced.

**Comment by ramyathammineni** [comment]
It would be difficult if there is no automation testing

**Comment by kavyaram15** [comment]
Lets at least try to implement the manual testing then

**Review by imsarahkhan — APPROVED** [review]

**Review by ramyathammineni — APPROVED** [review]

**Pull request closed without merging**
