### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by imsarahkhan**
Test Cases

Are all test cases for release 1 working?

### CODE REVIEW

**Comment by imsarahkhan** [comment]
Working on the email validation still.

**Comment by ramyathammineni** [comment]
Just final fixing to a few of the test cases.

**Comment by kavyaram15** [comment]
Working on the email validation.

**Review by ramyathammineni — APPROVED** [review]
Only few test cases are working and few redundant test cases observed

**Comment by imsarahkhan** [comment]
> Only few test cases are working and few redundant test cases observed

Ok

**Review by kavyaram15 — APPROVED** [review]
We can implement manual test cases since we tried unity.h testing framework and its not importing properly in clion.

**Comment by imsarahkhan** [comment]
> We can implement manual test cases since we tried unity.h testing framework and its not importing properly in clion.

Yes I agree

**Pull request closed without merging**
