### PR TITLE
modify_trip functionality

### PR DESCRIPTION
**Pull request by ramyathammineni**
As we are using the files concept, we are unable to add the passengers or remove the passengers.

### CODE REVIEW

**Comment by imsarahkhan** [comment]
Due to files, it is difficult to change the booking type. Overall the complete modify function is getting difficult to implement.

**Review by kavyaram15 — COMMENTED** [review]
Tried implementing changes to only users who are booking only two services instead of 3 services (flight, hotel and car). But this too didn't work well with the requirement.

**Review by imsarahkhan — APPROVED** [review]
I think it is better to move the modify trip function to future work as it is not working out and causing errors to the overall program.

**Comment by ramyathammineni** [comment]
> I think it is better to move the modify trip function to future work as it is not working out and causing errors to the overall program.

I agree with you its better we move it to future work.

**Review by kavyaram15 — APPROVED** [review]
Even I tried few other ways to implement the functionality I agree we should move this to the future work

**Pull request merged**
