### PR TITLE
Login functionality - return types issue

### PR DESCRIPTION
**Pull request by ramyathammineni**

### CODE REVIEW

**Review by imsarahkhan — CHANGES_REQUESTED** [review]
Try to use 2 flag values

**Comment by ramyathammineni** [comment]
> Try to use 2 flag values

Yeah that works now

**Review by imsarahkhan — APPROVED** [review]

**Review by kavyaram15 — APPROVED** [review]
Reviewed its good now

**Comment by ramyathammineni** [comment]
It working as per our requirement

**Pull request closed without merging**
