### PR TITLE
Signup functionality issue

### PR DESCRIPTION
**Pull request by kavyaram15**
There is an issue while taking the user inputs using scanf function

### CODE REVIEW

**Review by imsarahkhan — CHANGES_REQUESTED** [review]
Please use this "%[^\n]s" to read the user the input along with spaces

**Comment by ramyathammineni** [comment]
> Please use this "%[^\n]s" to read the user the input along with spaces

Yeah it works

**Review by imsarahkhan — APPROVED** [review]
Great!

**Review by ramyathammineni — CHANGES_REQUESTED** [review]
We can even use gets function as well

**Comment by kavyaram15** [comment]
> We can even use gets function as well

Yeah I have used gets function and it worked well

**Review by ramyathammineni — APPROVED** [review]
Looks good then

**Pull request merged**
